font:
  normal:
    family: "Source Code Pro"
    style: Medium
  bold:
    family: "Source Code Pro"
    style: Bold
  italic:
    family: "Source Code Pro"
    style: Italic
  size: 13.0

# Colors (Dracula PRO - Van Helsing)
colors:
  # Default colors
  primary:
    background: '0x0b0d0f'
    foreground: '0xf8f8f2'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  cursor:
    text: '0x414d58'
    cursor: '0xf8f8f2'

  # Selection colors
  #
  # Colors which should be used to draw the selection area. If selection
  # background is unset, selection color will be the inverse of the cell colors.
  # If only text is unset the cell text color will remain the same.
  selection:
    text: '0xf8f8f2'
    background: '0x414d58'

  # Normal colors
  normal:
    black:   '0x0b0d0f'
    red:     '0xff9580'
    green:   '0x8aff80'
    yellow:  '0xffff80'
    blue:    '0x9580ff'
    magenta: '0xff80bf'
    cyan:    '0x80ffea'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x0b0d0f'
    red:     '0xffaa99'
    green:   '0xa2ff99'
    yellow:  '0xffff99'
    blue:    '0xaa99ff'
    magenta: '0xff99cc'
    cyan:    '0x99ffee'
    white:   '0xffffff'

background_opacity: 0.85
