font:
  normal:
    family: "Source Code Pro"
    style: Medium
  bold:
    family: "Source Code Pro"
    style: Bold
  italic:
    family: "Source Code Pro"
    style: Italic
  size: 13.0

# Colors (Iceberg Dark)
# https://github.com/alacritty/alacritty/wiki/Color-schemes#iceberg
colors:
  # Default colors
  primary:
    background: '#161821'
    foreground: '#d2d4de'

  # Normal colors
  normal:
    black:   '#161821'
    red:     '#e27878'
    green:   '#b4be82'
    yellow:  '#e2a478'
    blue:    '#84a0c6'
    magenta: '#a093c7'
    cyan:    '#89b8c2'
    white:   '#c6c8d1'

  # Bright colors
  bright:
    black:   '#6b7089'
    red:     '#e98989'
    green:   '#c0ca8e'
    yellow:  '#e9b189'
    blue:    '#91acd1'
    magenta: '#ada0d3'
    cyan:    '#95c4ce'
    white:   '#d2d4de'
background_opacity: 0.95
