#!/bin/sh

for i in `seq 1 ${#}`
do
PLTNAME=$(basename $1)
DIR=$(dirname $1)
gnuplot<<EOF
cd "$DIR"
set terminal postscript eps enhanced color solid
set out "${PLTNAME%plt}eps"
load "$PLTNAME"
EOF
shift
done
